# Generated by Django 6.0.4 on 2026-04-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HealthReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("summary", models.TextField()),
                ("completion_rate", models.FloatField(default=0)),
                ("total_points", models.IntegerField(default=0)),
                ("recommendations", models.TextField(blank=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="WeeklyAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start", models.DateField()),
                ("total_habits", models.IntegerField(default=0)),
                ("completed_habits", models.IntegerField(default=0)),
                ("completion_rate", models.FloatField(default=0)),
                ("avg_energy", models.FloatField(default=0)),
                ("points_earned", models.IntegerField(default=0)),
                ("best_day", models.CharField(blank=True, max_length=20)),
                ("health_score", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
