# Generated by Django 6.0.4 on 2026-04-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fitness", "Fitness"),
                            ("hydration", "Hydration"),
                            ("sleep", "Sleep"),
                            ("nutrition", "Nutrition"),
                            ("mindfulness", "Mindfulness"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("target_value", models.FloatField(blank=True, null=True)),
                ("target_unit", models.CharField(blank=True, max_length=50)),
                ("deadline", models.DateField(blank=True, null=True)),
                ("color", models.CharField(default="#6C63FF", max_length=7)),
                ("icon", models.CharField(default="🎯", max_length=50)),
                ("progress_percent", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("custom", "Custom"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("scheduled_time", models.TimeField(blank=True, null=True)),
                ("duration_minutes", models.IntegerField(default=15)),
                ("streak_count", models.IntegerField(default=0)),
                ("best_streak", models.IntegerField(default=0)),
                ("completion_rate", models.FloatField(default=0)),
                ("points_per_completion", models.IntegerField(default=10)),
                ("is_active", models.BooleanField(default=True)),
                ("color", models.CharField(default="#6C63FF", max_length=7)),
                ("icon", models.CharField(default="✅", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="HabitLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("completed", models.BooleanField(default=False)),
                (
                    "mood",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("great", "😊 Great"),
                            ("good", "🙂 Good"),
                            ("neutral", "😐 Neutral"),
                            ("bad", "😕 Bad"),
                            ("terrible", "😞 Terrible"),
                        ],
                        max_length=20,
                    ),
                ),
                ("energy_level", models.IntegerField(default=5)),
                ("notes", models.TextField(blank=True)),
                ("duration_actual", models.IntegerField(blank=True, null=True)),
                ("points_earned", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MicroTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
                ("duration_minutes", models.IntegerField(default=5)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("points", models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name="Nudge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                (
                    "nudge_type",
                    models.CharField(
                        choices=[
                            ("motivational", "Motivational"),
                            ("reminder", "Reminder"),
                            ("smart", "Smart"),
                            ("achievement", "Achievement"),
                        ],
                        default="smart",
                        max_length=30,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
