# Generated by Django 6.0.4 on 2026-04-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AICoachMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Insight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("pattern", "Pattern"),
                            ("energy", "Energy"),
                            ("mood", "Mood"),
                            ("consistency", "Consistency"),
                            ("recommendation", "Recommendation"),
                            ("medical", "Medical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("icon", models.CharField(default="💡", max_length=10)),
                ("is_positive", models.BooleanField(default=True)),
                ("is_read", models.BooleanField(default=False)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MoodEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mood",
                    models.CharField(
                        choices=[
                            ("great", "😊 Great"),
                            ("good", "🙂 Good"),
                            ("neutral", "😐 Neutral"),
                            ("bad", "😕 Bad"),
                            ("terrible", "😞 Terrible"),
                        ],
                        max_length=20,
                    ),
                ),
                ("energy_level", models.IntegerField(default=5)),
                ("note", models.TextField(blank=True)),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
