# Generated by Django 6.0.4 on 2026-04-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='proposed_ai_plan',
            field=models.TextField(blank=True, help_text='AI generated plan awaiting approval', null=True),
        ),
    ]
