# Generated by Django 6.0.4 on 2026-04-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='confirmed_ai_plan',
            field=models.TextField(blank=True, help_text='Doctor approved AI plan', null=True),
        ),
    ]
